CREATE TABLE ORDERDETAIL (
  "订单编号" VARCHAR2(20 BYTE) ,
  "外部平台单号" VARCHAR2(1000 BYTE) NOT NULL ,
  "店铺名称" VARCHAR2(50 BYTE) ,
  "订单类型" VARCHAR2(50 BYTE) NOT NULL ,
  "处理状态" VARCHAR2(20 BYTE) NOT NULL ,
  "付款状态" VARCHAR2(20 BYTE) NOT NULL ,
  "发货状态" VARCHAR2(20 BYTE) NOT NULL ,
  "电话" VARCHAR2(61 BYTE) ,
  "手机" VARCHAR2(52 BYTE) ,
  "平台发货状态" VARCHAR2(20 BYTE) NOT NULL ,
  "物流公司" VARCHAR2(200 BYTE) ,
  "快递公司名称" VARCHAR2(50 BYTE) ,
  "快递单号" VARCHAR2(50 BYTE) NOT NULL ,
  "产品总金额" NUMBER(19,4) ,
  "订单总金额" NUMBER(19,4) ,
  "实收金额" NUMBER(19,4) ,
  "实收快递费" NUMBER(19,4) ,
  "实付快递费" NUMBER(19,4) NOT NULL ,
  "快递代收金额" NUMBER(19,4) ,
  "订单净重" NUMBER(20,3) ,
  "订单毛重" NUMBER(9,3) NOT NULL ,
  "付款日期" CHAR(19 BYTE) NOT NULL ,
  "审单日期" CHAR(19 BYTE) NOT NULL ,
  "打印日期" CHAR(19 BYTE) NOT NULL ,
  "验货日期" CHAR(19 BYTE) NOT NULL ,
  "发货日期" CHAR(19 BYTE) NOT NULL ,
  "买家ID" VARCHAR2(50 BYTE) ,
  "收货人" VARCHAR2(100 BYTE) ,
  "收货地址" VARCHAR2(1000 BYTE) ,
  "收货省" VARCHAR2(100 BYTE) ,
  "收货市" VARCHAR2(100 BYTE) ,
  "收货县" VARCHAR2(100 BYTE) ,
  "产品编号" VARCHAR2(50 BYTE) ,
  "条形码" VARCHAR2(255 BYTE) ,
  "产品名称" VARCHAR2(1000 BYTE) ,
  "规格" VARCHAR2(255 BYTE) ,
  "网店品名" VARCHAR2(261 BYTE) NOT NULL ,
  "网店规格" VARCHAR2(100 BYTE) ,
  "订货数量" NUMBER(10) ,
  "赠品数量" NUMBER(10) NOT NULL ,
  "产品报价" NUMBER(19,4) ,
  "产品报价总金额" NUMBER(19,4) ,
  "产品打折金额" NUMBER(19,4) ,
  "产品抵扣分摊金额" NUMBER(19,4) ,
  "产品成交金额" NUMBER(19,4) ,
  "产品成交单价" NUMBER(19,4) ,
  "产品重量小计" NUMBER(20,3) ,
  "产品缺货状态" VARCHAR2(20 BYTE) ,
  "产品退货到货数量" NUMBER(10) NOT NULL ,
  "签收时间" CHAR(19 BYTE) NOT NULL ,
  "省区域代码" VARCHAR2(50 BYTE) ,
  "市区域代码" VARCHAR2(50 BYTE) ,
  "区县区域代码" VARCHAR2(50 BYTE) ,
  "旗帜颜色" VARCHAR2(20 BYTE) ,
  "打折金额" VARCHAR2(50 BYTE) ,
  "安装服务商" VARCHAR2(100 BYTE) ,
  "保价" NUMBER(1) ,
  "订单促销信息" VARCHAR2(200 BYTE) ,
  "买家留言" CLOB ,
  "发票抬头" VARCHAR2(255 BYTE) ,
  "客服备注" CLOB ,
  "子订单编号" VARCHAR2(1000 BYTE) 
)
